version: "3"

services:

  mycroft:
    container_name: mycroft
    build:
      context: ./
    volumes:
      - /dev:/dev
      - ./mycroft/opt:/opt/mycroft
      - ./mycroft/home:/home/mycroft/.mycroft
      - ./mycroft/virtualenvs:/home/mycroft/.virtualenvs
    restart: always
    network_mode: host
    privileged: true
